"use client";

import Link from "next/link";
import { useEffect } from "react";

import { Badge } from "@/components/ui/badge";
import { deployWorkflow, listWorkflows } from "@/lib/console-api";
import { useProjectContextStore } from "@/lib/stores/project-context-store";
import { useWorkflowStore } from "@/lib/stores/workflow-store";

export default function WorkflowsPage() {
  const context = useProjectContextStore((state) => state.context);
  const workflows = useWorkflowStore((state) => state.workflows);
  const setWorkflows = useWorkflowStore((state) => state.setWorkflows);

  useEffect(() => {
    if (!context.institutionId || !context.projectId) {
      return;
    }
    listWorkflows({ institutionId: context.institutionId, projectId: context.projectId }).then((payload) =>
      setWorkflows(payload.workflows)
    );
  }, [context.institutionId, context.projectId, setWorkflows]);

  const deploy = async (workflowId: string) => {
    await deployWorkflow({ institutionId: context.institutionId, projectId: context.projectId }, workflowId);
    const payload = await listWorkflows({ institutionId: context.institutionId, projectId: context.projectId });
    setWorkflows(payload.workflows);
  };

  return (
    <div className="space-y-4">
      <h2 className="text-2xl font-semibold">Workflows</h2>
      <div className="overflow-hidden rounded-md border border-[var(--border-default)] bg-[var(--bg-secondary)]">
        <table className="w-full text-left text-sm">
          <thead className="bg-[var(--bg-tertiary)] text-[var(--text-secondary)]">
            <tr>
              <th className="px-4 py-3">Name</th>
              <th className="px-4 py-3">Version</th>
              <th className="px-4 py-3">Generated by AI</th>
              <th className="px-4 py-3">Status</th>
              <th className="px-4 py-3">Actions</th>
            </tr>
          </thead>
          <tbody>
            {workflows.map((workflow) => (
              <tr key={workflow.id} className="border-t border-[var(--border-default)]">
                <td className="px-4 py-3">{workflow.name}</td>
                <td className="px-4 py-3">v{workflow.version}</td>
                <td className="px-4 py-3">
                  {workflow.is_ai_generated ? (
                    <Badge className="border-[#2f1f40] bg-[#1e1030] text-[#c084fc]">AI</Badge>
                  ) : (
                    <Badge variant="outline" className="border-[var(--border-default)] text-[var(--text-secondary)]">
                      Manual
                    </Badge>
                  )}
                </td>
                <td className="px-4 py-3">{workflow.deployed ? "Deployed" : "Draft"}</td>
                <td className="px-4 py-3">
                  <div className="flex items-center gap-3">
                    <Link href={`/console/workflows/${workflow.id}`} className="underline text-[var(--text-secondary)]">
                      View
                    </Link>
                    <Link href={`/console/workflows/${workflow.id}/edit`} className="underline text-[var(--text-secondary)]">
                      Edit
                    </Link>
                    {!workflow.deployed && (
                      <button className="underline text-[#86efac]" onClick={() => deploy(workflow.id)}>
                        Deploy
                      </button>
                    )}
                  </div>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
