export default function ArchitectManualPage() {
  return (
    <>
      {/* Badge */}
      <div className="inline-flex items-center gap-2 rounded-full border border-indigo-900/50 bg-indigo-900/20 px-3 py-1 text-xs text-indigo-400 mb-6 font-sans">
        Manual · Architect
      </div>

      <h1 className="text-4xl font-bold tracking-tight mb-4">The Architect Page</h1>
      <p className="text-lg text-gray-400 leading-relaxed mb-10">
        Architect is where you compose your deployed workflows into a coherent ERP domain structure
        and compile it into a versioned, production-ready API. Think of it as the layer above
        individual workflows — the place where you design <em>how your institution&apos;s systems connect</em>.
      </p>

      {/* ── Role in the flow ── */}
      <h2 className="text-2xl font-bold mt-12 mb-4">Where Architect Fits</h2>
      <p className="text-gray-300 mb-4">
        The Orquestra product flow is linear:
      </p>

      <div className="rounded-md border border-[var(--border-default)] bg-[var(--bg-secondary)] p-5 mb-6 font-mono text-sm text-gray-300">
        <span className="text-blue-400">1. Build Workflows</span>
        {" → "}
        <span className="text-indigo-400">2. Design in Architect</span>
        {" → "}
        <span className="text-green-400">3. Compile</span>
        {" → "}
        <span className="text-amber-400">4. Call Runtime API</span>
      </div>

      <ul className="list-disc list-inside text-gray-400 space-y-2 mb-8 text-sm">
        <li>Workflows define individual processes (admissions, payroll, HR onboarding).</li>
        <li>Architect groups those workflows into domains and describes how they relate.</li>
        <li>Compiling produces a versioned API key and webhook secret that grant access to the Runtime API.</li>
        <li>The Runtime API is what your application actually calls to submit and track applications.</li>
      </ul>

      {/* ── Getting there ── */}
      <h2 className="text-2xl font-bold mt-12 mb-4">Getting to the Architect Page</h2>
      <p className="text-gray-300 mb-6">
        Navigate to <strong>Architect</strong> in the Console left sidebar, or click{" "}
        <strong>Deploy &amp; Continue</strong> on the Workflow Canvas — that button deploys your workflow
        and takes you straight to Architect. You will always land on the same architecture for your
        current project; Orquestra auto-creates one if it doesn&apos;t exist yet.
      </p>

      {/* ── Page layout ── */}
      <h2 className="text-2xl font-bold mt-12 mb-4">Page Layout</h2>

      <div className="space-y-4 mb-10">
        <div className="rounded-md border border-[var(--border-default)] bg-[var(--bg-secondary)] p-5">
          <h3 className="font-bold text-white mb-1">Domain Cards Grid</h3>
          <p className="text-gray-400 text-sm">
            The main body of the page. Each card represents an ERP domain (e.g., Admissions, Finance,
            Human Resources). Domains are generated by the AI when you describe your institution in the
            NLP prompt bar. Each card shows the domain name, linked workflow (if any), and a button to
            link a deployed workflow to that domain.
          </p>
        </div>

        <div className="rounded-md border border-[var(--border-default)] bg-[var(--bg-secondary)] p-5">
          <h3 className="font-bold text-white mb-1">NLP Prompt Bar</h3>
          <p className="text-gray-400 text-sm">
            The text input at the top of the page. Type a natural language description of what you want
            to add or change in your ERP structure. The AI interprets your intent and applies the
            corresponding operation to the domain graph — adding domains, renaming them, removing them,
            or restructuring how they relate. Each prompt is versioned in the history panel.
          </p>
        </div>

        <div className="rounded-md border border-[var(--border-default)] bg-[var(--bg-secondary)] p-5">
          <h3 className="font-bold text-white mb-1">Compile Panel</h3>
          <p className="text-gray-400 text-sm">
            The right-side or bottom panel that appears when you are ready to compile. You select which
            deployed workflows to include, give the API key a name, and click <strong>Compile</strong>.
            The result is a versioned architecture snapshot with a one-time-visible API key and webhook
            secret.
          </p>
        </div>

        <div className="rounded-md border border-[var(--border-default)] bg-[var(--bg-secondary)] p-5">
          <h3 className="font-bold text-white mb-1">Version History</h3>
          <p className="text-gray-400 text-sm">
            Every compile creates a new architecture version (v1, v2, v3…). The version history panel
            shows all past compilations with their timestamps. Old versions remain valid — their API keys
            continue to work until you explicitly revoke them in the API Keys section.
          </p>
        </div>
      </div>

      {/* ── NLP prompt bar ── */}
      <h2 className="text-2xl font-bold mt-12 mb-4">Using the NLP Prompt Bar</h2>
      <p className="text-gray-300 mb-4">
        The prompt bar is the primary way to build your domain graph. Type a description of the change
        you want, press <strong>Apply</strong>, and the AI updates the architecture graph accordingly.
        You do not need to know any specific syntax — plain English works.
      </p>

      <div className="rounded-md border border-[var(--border-default)] bg-[var(--bg-secondary)] p-5 mb-6">
        <h3 className="font-bold text-white mb-3 text-sm">Example Prompts</h3>
        <div className="space-y-2 font-mono text-xs text-gray-300">
          <div className="p-2 rounded bg-[#0f0f12] border border-[var(--border-default)]">Add admissions and financial aid domains</div>
          <div className="p-2 rounded bg-[#0f0f12] border border-[var(--border-default)]">Include HR onboarding and payroll processing sections</div>
          <div className="p-2 rounded bg-[#0f0f12] border border-[var(--border-default)]">Remove the procurement domain</div>
          <div className="p-2 rounded bg-[#0f0f12] border border-[var(--border-default)]">Rename &apos;student_affairs&apos; to &apos;student_success&apos;</div>
          <div className="p-2 rounded bg-[#0f0f12] border border-[var(--border-default)]">Add a research grants domain with a compliance link to admissions</div>
        </div>
      </div>

      <p className="text-gray-300 mb-4">
        Each prompt result records:
      </p>
      <ul className="list-disc list-inside text-gray-400 space-y-2 mb-8 text-sm">
        <li>The operation applied (add_domain, remove_domain, rename, etc.)</li>
        <li>The AI&apos;s rationale — the reasoning behind the structural decision</li>
        <li>A diff summary describing what changed relative to the previous version</li>
        <li>The intent classification (the AI&apos;s interpretation of your instruction)</li>
      </ul>

      <div className="p-4 border-l-2 border-amber-500 bg-amber-500/10 text-amber-200 mb-10 rounded-r-md text-sm">
        <strong>Redirect intent:</strong> If your prompt sounds more like a workflow creation request
        (e.g., "add a scholarship review process"), the AI will classify it as a redirect and
        suggest you build a workflow first. Follow the suggestion link to return to the Workflow
        Canvas, then come back to Architect after deploying.
      </div>

      {/* ── Domain cards ── */}
      <h2 className="text-2xl font-bold mt-12 mb-4">Domain Cards</h2>
      <p className="text-gray-300 mb-4">
        Each domain card represents a functional area of your institution&apos;s ERP. Domains are
        structural labels — they have no logic of their own. Their purpose is to:
      </p>
      <ul className="list-disc list-inside text-gray-400 space-y-2 mb-6 text-sm">
        <li>Organise deployed workflows into meaningful categories</li>
        <li>Define the scope of what gets compiled into a given architecture version</li>
        <li>Appear in the architecture visualisation so stakeholders can understand the system at a glance</li>
      </ul>

      <div className="rounded-md border border-[var(--border-default)] bg-[var(--bg-secondary)] p-5 mb-8">
        <h3 className="font-bold text-white mb-2">Linking a Workflow to a Domain</h3>
        <p className="text-gray-400 text-sm mb-3">
          Each domain card has a <strong>Link Workflow</strong> button. Click it to open a dropdown of
          all deployed workflows in your project. Select the workflow that belongs to this domain. A
          domain can be linked to one workflow; one workflow can be linked to multiple domains if
          needed (e.g., a shared review process used by Admissions and Financial Aid).
        </p>
        <p className="text-gray-400 text-sm">
          Only deployed workflows appear in the list. If a workflow you built does not appear,
          go back to Workflows and deploy it first.
        </p>
      </div>

      {/* ── Compile ── */}
      <h2 className="text-2xl font-bold mt-12 mb-4">Compiling an Architecture Version</h2>
      <p className="text-gray-300 mb-4">
        When you are satisfied with your domain structure and have linked all the workflows you want to
        expose, click <strong>Compile</strong>. This action:
      </p>

      <div className="space-y-3 mb-8">
        {[
          ["Creates an Architecture Version snapshot", "The current state of the domain graph is frozen into an immutable version record (v1, v2, etc.)."],
          ["Links workflows at their current version", "Each selected workflow is pinned at its current deployed version. If you later update a workflow (creating v2), the architecture version still points at v1 until you recompile."],
          ["Generates a versioned API key", "A unique key in the format sk_erp_v{n}_{random} is generated. It is shown once — copy it immediately and store it securely. Only the SHA-256 hash is stored in the database."],
          ["Generates a webhook secret", "A webhook signing secret in the format whsec_erp_{random} is also generated once. Used to verify event payloads sent to your endpoints."],
          ["Emits an architecture.compiled event", "Recorded in the event stream so you have an audit trail of every compile."],
        ].map(([title, desc]) => (
          <div key={title} className="rounded-md border border-[var(--border-default)] bg-[var(--bg-secondary)] p-4">
            <h3 className="font-bold text-white text-sm mb-1">{title}</h3>
            <p className="text-gray-400 text-sm">{desc}</p>
          </div>
        ))}
      </div>

      <div className="p-4 border-l-2 border-red-500 bg-red-500/10 text-red-200 mb-10 rounded-r-md text-sm">
        <strong>API key and webhook secret are shown exactly once.</strong> After you close or navigate
        away from the compile result, neither the raw key nor the raw secret can be retrieved again.
        If you lose them, compile again to generate a new version with fresh credentials.
      </div>

      {/* ── Using the key ── */}
      <h2 className="text-2xl font-bold mt-12 mb-4">Using the API Key</h2>
      <p className="text-gray-300 mb-4">
        The compiled API key authenticates calls to the <strong>Runtime API</strong> at{" "}
        <code>/api/v1/</code>. Pass it as a Bearer token:
      </p>
      <div className="rounded bg-[#0f0f12] border border-[var(--border-default)] p-4 font-mono text-xs text-green-400 mb-6">
        <div>POST /api/v1/applications</div>
        <div>Authorization: Bearer sk_erp_v1_abc123...</div>
        <div>Content-Type: application/json</div>
        <div className="mt-2 text-gray-500">{`{`}</div>
        <div className="text-gray-500 ml-4">{`"workflow_id": "wf_xyz...",`}</div>
        <div className="text-gray-500 ml-4">{`"applicant_data": { "score": 85, "name": "Alice" }`}</div>
        <div className="text-gray-500">{`}`}</div>
      </div>
      <p className="text-gray-300 mb-4">
        The key grants access to all workflows linked in the architecture version it was compiled from.
        Attempting to submit to a workflow not included in that version returns a <code>403 Forbidden</code>.
      </p>
      <p className="text-gray-300 mb-8">
        The key has no expiry by default. You can revoke it at any time from the{" "}
        <strong>API Keys</strong> section in the Console sidebar.
      </p>

      {/* ── Version history ── */}
      <h2 className="text-2xl font-bold mt-12 mb-4">Version History</h2>
      <p className="text-gray-300 mb-4">
        Every compile produces a new architecture version. Versions are additive — they do not
        invalidate previous ones. This means:
      </p>
      <ul className="list-disc list-inside text-gray-400 space-y-2 mb-6 text-sm">
        <li>v1 keys continue to work after you compile v2.</li>
        <li>Applications submitted through v1 workflows remain on v1 definitions.</li>
        <li>You can roll back by reverting to the credentials from an older version.</li>
        <li>Each version shows a graph snapshot of the domain structure at compile time.</li>
      </ul>
      <p className="text-gray-300 mb-8">
        To deprecate old versions, revoke their API keys from the API Keys management page. Once a
        key is revoked, any call using it returns <code>401 Unauthorized</code>.
      </p>

      {/* ── Architect vs Workflows ── */}
      <h2 className="text-2xl font-bold mt-12 mb-4">Architect vs Workflows — Key Differences</h2>
      <div className="overflow-hidden rounded-md border border-[var(--border-default)] mb-10">
        <table className="w-full text-sm">
          <thead className="bg-[var(--bg-secondary)]">
            <tr>
              <th className="text-left px-4 py-3 text-gray-300 font-semibold">Aspect</th>
              <th className="text-left px-4 py-3 text-gray-300 font-semibold">Workflows</th>
              <th className="text-left px-4 py-3 text-gray-300 font-semibold">Architect</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-[var(--border-default)]">
            {[
              ["What it defines", "Individual process logic (states, transitions, conditions)", "How processes relate as an institutional ERP system"],
              ["AI mode", "Mode A — Blueprint Generator", "Mode B — ERP Domain Composer"],
              ["Output", "Versioned workflow definition JSON", "Architecture version + API key + webhook secret"],
              ["Immutability", "Deployed workflows are immutable", "Each compile creates a new immutable version"],
              ["Runtime impact", "Direct — execution engine runs workflow states", "Indirect — determines which workflows the API key can access"],
              ["Who edits it", "Developer / process designer", "System architect / technical lead"],
            ].map(([aspect, wf, arch]) => (
              <tr key={aspect} className="hover:bg-[var(--bg-secondary)]/50">
                <td className="px-4 py-3 text-gray-300 font-medium">{aspect}</td>
                <td className="px-4 py-3 text-gray-400">{wf}</td>
                <td className="px-4 py-3 text-gray-400">{arch}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      {/* ── Common patterns ── */}
      <h2 className="text-2xl font-bold mt-12 mb-4">Common Patterns</h2>

      <div className="space-y-4 mb-10">
        <div className="rounded-md border border-[var(--border-default)] bg-[var(--bg-secondary)] p-5">
          <h3 className="font-bold text-white mb-2">Starting fresh with a new project</h3>
          <ol className="list-decimal list-inside text-gray-400 text-sm space-y-1">
            <li>Open Architect → type a prompt like <em>"I need admissions, financial aid, and HR domains"</em></li>
            <li>Three domain cards appear. Go build a workflow for each.</li>
            <li>Return to Architect, link each workflow to its domain.</li>
            <li>Compile → copy credentials → start calling the Runtime API.</li>
          </ol>
        </div>

        <div className="rounded-md border border-[var(--border-default)] bg-[var(--bg-secondary)] p-5">
          <h3 className="font-bold text-white mb-2">Adding a new workflow to an existing architecture</h3>
          <ol className="list-decimal list-inside text-gray-400 text-sm space-y-1">
            <li>Build and deploy the new workflow on the Workflow Canvas.</li>
            <li>Return to Architect → add a domain card for the new process.</li>
            <li>Link the new workflow to the new domain.</li>
            <li>Compile → a new version (e.g., v3) is created with all previous workflows plus the new one.</li>
            <li>Update your application to use the new API key for v3.</li>
          </ol>
        </div>

        <div className="rounded-md border border-[var(--border-default)] bg-[var(--bg-secondary)] p-5">
          <h3 className="font-bold text-white mb-2">Updating a workflow (new version)</h3>
          <ol className="list-decimal list-inside text-gray-400 text-sm space-y-1">
            <li>Make a new workflow with the same name → it gets version 2.</li>
            <li>In Architect, unlink the domain from v1 and link it to v2.</li>
            <li>Compile → the new architecture version pins workflows at their current version.</li>
            <li>Applications running on v1 continue unaffected; new applications use v2.</li>
          </ol>
        </div>
      </div>

      {/* ── Best practices ── */}
      <h2 className="text-2xl font-bold mt-12 mb-4">Best Practices</h2>
      <ul className="list-disc list-inside text-gray-400 space-y-3 mb-8 text-sm">
        <li>Build at least one workflow before opening Architect — the page shows available workflows when linking domains, and an empty list means nothing is available to compile.</li>
        <li>Name domains with consistent terminology that matches your institution&apos;s language — these names appear in the API and event payloads.</li>
        <li>Compile only when workflows are stable. Each compile uses a credential slot, and while old keys keep working, accumulating many versions adds management overhead.</li>
        <li>Store API keys in environment variables or a secrets manager immediately after copying. Never commit them to source control.</li>
        <li>Use the version history to understand your architecture&apos;s evolution. If something breaks after a compile, the previous version&apos;s credentials will still work as a rollback.</li>
        <li>Check the Console Event Stream after compiling — the <code>architecture.compiled</code> event confirms the operation was recorded successfully.</li>
      </ul>
    </>
  );
}
