"""add arch_workflows junction, link api_keys, add ai_prompt

Revision ID: 58fa2f5c1f90
Revises: 20260219_0001
Create Date: 2026-03-27 22:10:56.448889
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '58fa2f5c1f90'
down_revision = '20260219_0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arch_workflows',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('architecture_version_id', sa.String(), nullable=False),
    sa.Column('workflow_id', sa.String(), nullable=False),
    sa.Column('workflow_version', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['architecture_version_id'], ['architecture_versions.id'], ),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('architecture_version_id', 'workflow_id', name='uq_arch_version_workflow')
    )
    op.create_index(op.f('ix_arch_workflows_architecture_version_id'), 'arch_workflows', ['architecture_version_id'], unique=False)
    op.create_index('ix_arch_workflows_version', 'arch_workflows', ['architecture_version_id'], unique=False)
    op.create_index(op.f('ix_arch_workflows_workflow_id'), 'arch_workflows', ['workflow_id'], unique=False)
    op.add_column('api_keys', sa.Column('project_id', sa.String(), nullable=True))
    op.add_column('api_keys', sa.Column('architecture_version_id', sa.String(), nullable=True))
    op.add_column('api_keys', sa.Column('webhook_secret_hash', sa.String(length=64), nullable=True))
    op.add_column('api_keys', sa.Column('webhook_secret_prefix', sa.String(length=24), nullable=True))
    op.create_index(op.f('ix_api_keys_architecture_version_id'), 'api_keys', ['architecture_version_id'], unique=False)
    op.create_index(op.f('ix_api_keys_project_id'), 'api_keys', ['project_id'], unique=False)
    op.create_foreign_key(None, 'api_keys', 'architecture_versions', ['architecture_version_id'], ['id'])
    op.create_foreign_key(None, 'api_keys', 'projects', ['project_id'], ['id'])
    op.add_column('workflows', sa.Column('ai_prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflows', 'ai_prompt')
    op.drop_constraint(None, 'api_keys', type_='foreignkey')
    op.drop_constraint(None, 'api_keys', type_='foreignkey')
    op.drop_index(op.f('ix_api_keys_project_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_architecture_version_id'), table_name='api_keys')
    op.drop_column('api_keys', 'webhook_secret_prefix')
    op.drop_column('api_keys', 'webhook_secret_hash')
    op.drop_column('api_keys', 'architecture_version_id')
    op.drop_column('api_keys', 'project_id')
    op.drop_index(op.f('ix_arch_workflows_workflow_id'), table_name='arch_workflows')
    op.drop_index('ix_arch_workflows_version', table_name='arch_workflows')
    op.drop_index(op.f('ix_arch_workflows_architecture_version_id'), table_name='arch_workflows')
    op.drop_table('arch_workflows')
    # ### end Alembic commands ###
